### ISSUE TITLE
Left and right aligned small images are larger than expected

### ISSUE THREAD

**Issue by dannylonglegs** [pressbooks/pressbooks-jacobs#12]
### Description

Left and right aligned small images (with and without captions) are displaying too large.

### Steps to Reproduce

1. Navigate page 183 on 'After' pdf and page 181 on 'Before' pdf
2. Compare left aligned images and right aligned images

**Comment by greatislander** [comment]
Images used to have an arbitrary max-width of 80%; I'm closing for now. We can reinvestigate later if needed.
