### ISSUE TITLE
EPUB/MOBI: TOC styling updates

### ISSUE THREAD

**Issue by dannylonglegs** [pressbooks/pressbooks-jacobs#14]
### Description

- [ ] Add top margin to TOC front matter titles
- [ ] Add top margin to TOC chapter titles
- [ ] Add TOC page margins
- [ ] TOC chapter subtitle text-transform: Set to Italic
- [ ] TOC chapter author text-transform: Set to Italic
- [ ] MOBI: TOC chapter title font-family needs to be changed

Before:
![screen shot 2018-05-09 at 10 55 29 am](https://user-images.githubusercontent.com/21149722/39827459-fac952d0-5385-11e8-8b99-41e0d2c483b0.png)

After:
![screen shot 2018-05-09 at 10 55 43 am](https://user-images.githubusercontent.com/21149722/39827470-ffeb3422-5385-11e8-823b-147c85be3ef8.png)

**Comment by greatislander** [comment]
Fixed in pressbooks/pressbooks#1224.
