### ISSUE TITLE
 PDF/MOBI: Content breaks to next page on "Tracking Comparisons" chapter

### ISSUE THREAD

**Issue by dannylonglegs** [pressbooks/pressbooks-jacobs#16]
### Description

In "Tracking Comparisons" chapter (chapter 9), the content breaks to next page after the "Tests" header on both 'Before' and 'After' pdf's.

### Steps to Reproduce

1. Navigate to page 64 on 'Before' and 'After' pdf's
2. Scroll to 'Tests' Header

**Comment by greatislander** [comment]
See pressbooks/buckram#127.
