### ISSUE TITLE
 Content breaks to next page on "Tracking Comparisons" chapter

### ISSUE THREAD

**Issue by dannylonglegs** [pressbooks/pressbooks-jacobs#7]
### Description

In "Tracking Comparisons" chapter, the content breaks to next page after the "Tests" header on both 'Before' and 'After' pdf's.

### Steps to Reproduce

1. Navigate to page 61 on 'Before' and 60 on 'After' pdf's
2. Scroll to 'Tests' header

**Comment by greatislander** [comment]
See https://github.com/pressbooks/buckram/issues/127
